using in

pub_hdrs = hxx{** -fineftp_version}

./: $pub_hdrs hxx{fineftp_version}

hxx{fineftp_version}: in{fineftp_version} $src_root/manifest
{
  flavor = cmake
}
hxx{fineftp_export}@./: cxx.importable = false

# Install into the fineftp/ subdirectory of, say, /usr/include/
# recreating subdirectories.
#
hxx{*}:
{
  install         = include/fineftp/
  install.subdirs = true
}
