using in

pub_hdrs = hxx{** -fineftp_version}

./: $pub_hdrs hxx{fineftp_version}

hxx{fineftp_version}: in{fineftp_version} $src_root/manifest
{
  in.symbol = '@'

  PROJECT_VERSION_MAJOR = $version.major
  PROJECT_VERSION_MINOR = $version.minor
  PROJECT_VERSION_PATCH = $version.patch
}
hxx{fineftp_export}@./: cxx.importable = false

# Install into the fineftp/ subdirectory of, say, /usr/include/
# recreating subdirectories.
#
hxx{*}:
{
  install         = include/fineftp/
  install.subdirs = true
}
