using in

pub_hdrs = hxx{**}

./: $pub_hdrs

hxx{fineftp_version}: in{fineftp_version} $src_root/manifest
{
  flavor = cmake
}
hxx{finftp_export}@./: cxx.importable = false

# Install into the fineftp/ subdirectory of, say, /usr/include/
# recreating subdirectories.
#
hxx{*}:
{
  install         = include/fineftp/
  install.subdirs = true
}
